### ISSUE TITLE
Change `Ronin::Vulns::SSTI::ESCAPES` to be a `Hash`

### ISSUE THREAD

**Issue by postmodern** [ronin-rb/ronin-vulns#55]
Change `Ronin::Vulns::SSTI::ESCAPES` to be a `Hash` and assign symbol names to the escape `Proc`s. Also change `SSTI#initialize` to accept a `Symbol` name as well as a `Proc`, and lookup `Symbol`s in the `ESCAPES` `Hash`.

* [x] `{{expr}}` - Liquid / Jinja
* [ ] `${expr}` - JavaScript?
* [ ] `${{expr}}` - ????
* [ ] `#{expr}` - Ruby?
* [x] `<%= expr %>` - ERB

**Comment by postmodern** [comment]
@AI-Mozi I pushed the `ssti_symbol_names` branch. The `escape:` keyword now accepts a Symbol value, which resolves to a Proc and sets `escape` like normal, but also sets `template_syntax` which should allow us to save that key piece of information to the database.

(Note: I went with `template_syntax` since it's describing the syntax of template interpolation, not the engine itself; think of template engine as just the implementation of a template syntax.)

**Comment by postmodern** [comment]
If there are no objections/feedback, I can merge this branch into the 0.2.0 branch.

**Comment by AI-Mozi** [comment]
Looks good to me :)

**Comment by postmodern** [comment]
I ended up renaming `template_syntax` to `escape_type` so it's clear that it relates to `escape:` and `#escape`.

**Comment by postmodern** [comment]
Implemented in 842bffa.
